// This file was automatically generated by crowbar.

namespace ply {

constexpr Label LABEL_enum{2};
constexpr Label LABEL_enum_{8};
constexpr Label LABEL_pointer{16};
constexpr Label LABEL_struct{26};
constexpr Label LABEL_struct_{34};

} // namespace ply
