// This file was automatically generated by crowbar.

#include <ply-runtime.h>

namespace ply {

void init_predefined_labels() {
#define PLY_INIT_PREDEFINED_LABEL(text) \
    { \
        u32 idx = g_labelStorage.insert(#text).idx; \
        PLY_ASSERT(idx == LABEL_##text.idx); \
        PLY_UNUSED(idx); \
    }
    PLY_INIT_PREDEFINED_LABEL(compile_options);
    PLY_INIT_PREDEFINED_LABEL(config);
    PLY_INIT_PREDEFINED_LABEL(config_list);
    PLY_INIT_PREDEFINED_LABEL(config_options);
    PLY_INIT_PREDEFINED_LABEL(dependencies);
    PLY_INIT_PREDEFINED_LABEL(enum);
    PLY_INIT_PREDEFINED_LABEL(enum_);
    PLY_INIT_PREDEFINED_LABEL(executable);
    PLY_INIT_PREDEFINED_LABEL(generate);
    PLY_INIT_PREDEFINED_LABEL(include_directories);
    PLY_INIT_PREDEFINED_LABEL(library);
    PLY_INIT_PREDEFINED_LABEL(link_libraries);
    PLY_INIT_PREDEFINED_LABEL(link_objects_directly);
    PLY_INIT_PREDEFINED_LABEL(pointer);
    PLY_INIT_PREDEFINED_LABEL(prebuild_step);
    PLY_INIT_PREDEFINED_LABEL(preprocess_labels);
    PLY_INIT_PREDEFINED_LABEL(preprocessor_definitions);
    PLY_INIT_PREDEFINED_LABEL(private);
    PLY_INIT_PREDEFINED_LABEL(public);
    PLY_INIT_PREDEFINED_LABEL(source_files);
    PLY_INIT_PREDEFINED_LABEL(struct);
    PLY_INIT_PREDEFINED_LABEL(struct_);
#undef PLY_INIT_PREDEFINED_LABEL
}

} // namespace ply
