// This file was automatically generated by crowbar.

#include <ply-runtime.h>
#include <ply-runtime/predefined_labels.h>

namespace ply {

void init_predefined_labels() {
#define PLY_INIT_PREDEFINED_LABEL(text) \
    { \
        u32 idx = g_labelStorage.insert(#text).idx; \
        PLY_ASSERT(idx == LABEL_##text.idx); \
        PLY_UNUSED(idx); \
    }
    PLY_INIT_PREDEFINED_LABEL(enum);
    PLY_INIT_PREDEFINED_LABEL(enum_);
    PLY_INIT_PREDEFINED_LABEL(pointer);
    PLY_INIT_PREDEFINED_LABEL(struct);
    PLY_INIT_PREDEFINED_LABEL(struct_);
#undef PLY_INIT_PREDEFINED_LABEL
}

} // namespace ply
